import React from 'react';
import { 
  X, 
  Download, 
  FileText, 
  Activity, 
  ShieldAlert,
  Radio,
  Zap,
  Thermometer,
  Cpu
} from 'lucide-react';
import { Badge } from '../common/Badge';

export const RecordDetailModal = ({ record, onClose }) => {
  if (!record) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-container" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <div className="modal-title-group">
            <FileText size={16} className="text-blue" />
            <span className="modal-title font-mono">{record.recordId} • {record.mode} RECORD</span>
            <Badge status={record.status} />
          </div>
          <button className="modal-close-btn" onClick={onClose}>
            <X size={16} />
          </button>
        </div>

        {/* Modal Body */}
        <div className="modal-body">
          {/* Top metadata grid */}
          <div className="modal-meta-grid font-mono">
            <div className="meta-box">
              <span className="meta-label">TARGET MOTOR IDENTIFIER</span>
              <span className="meta-value font-bold text-blue">{record.motorId ? `${record.motorId} — ` : ''}{record.motor}</span>
            </div>
            <div className="meta-box">
              <span className="meta-label">SOURCE TYPE (SECTION 13)</span>
              <span className="meta-value font-bold text-emerald">
                <span className={`badge ${
                  record.sourceType === 'ESP32'
                    ? 'badge-healthy'
                    : record.sourceType === 'EXTERNAL_LAPTOP' 
                    ? 'badge-healthy' 
                    : record.sourceType === 'OFFLINE_FILE'
                    ? 'badge-info'
                    : 'badge-muted'
                } badge-sm font-mono`}>
                  {record.sourceType || 'ESP32'}
                </span>
              </span>
            </div>
            <div className="meta-box">
              <span className="meta-label">DATA SOURCE / FILE</span>
              <span className="meta-value text-blue">{record.source}</span>
            </div>
            <div className="meta-box">
              <span className="meta-label">TIMESTAMP</span>
              <span className="meta-value">{record.date} {record.time}</span>
            </div>
            <div className="meta-box">
              <span className="meta-label">HEALTH SCORE</span>
              <span className="meta-value font-bold">{record.health} / 100</span>
            </div>
            <div className="meta-box">
              <span className="meta-label">SUSPECTED ANOMALY</span>
              <span className="meta-value text-red">{record.notes || 'Nominal Operation'}</span>
            </div>
          </div>

          {record.referenceDatasetLabel && record.referenceDatasetLabel !== 'None' && (
            <div className="reference-label-modal-box font-mono" style={{ background: '#fffbeb', border: '1px solid #fde68a', padding: '8px 12px', borderRadius: '2px', marginBottom: '12px' }}>
              <span className="text-amber font-bold text-xs">REFERENCE DATASET LABEL: </span>
              <span className="text-blue font-bold text-xs">{record.referenceDatasetLabel}</span>
              <div className="text-muted text-xs mt-2" style={{ color: '#78350f' }}>
                Note: This label was supplied in dataset file metadata and is not an automated diagnosis generated by this system.
              </div>
            </div>
          )}

          {/* Captured Telemetry Snapshot (Physical Transducers + Extracted Features) */}
          <div className="modal-section-card">
            <div className="section-card-title">
              <Activity size={13} className="text-blue" />
              <span>RECORDED TELEMETRY & EXTRACTED FEATURES</span>
            </div>
            <div className="eng-table-container">
              <table className="eng-table font-mono">
                <thead>
                  <tr>
                    <th>CHANNEL / PARAMETER</th>
                    <th>PROVENANCE</th>
                    <th>CAPTURED VALUE</th>
                    <th>EXTENDED METRICS</th>
                    <th>STATUS</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="font-bold text-blue">VIBRATION (IEPE)</td>
                    <td>Physical Transducer</td>
                    <td>{record.vibrationRms != null ? `${record.vibrationRms} mm/s RMS` : '—'}</td>
                    <td>Peak: {record.vibrationPeak ? `${record.vibrationPeak} mm/s` : '—'} • Crest: {record.crestFactor != null ? record.crestFactor : '—'} • Kurtosis: {record.kurtosis != null ? record.kurtosis : '—'}</td>
                    <td><Badge status={record.status} size="sm" /></td>
                  </tr>
                  <tr>
                    <td className="font-bold">CURRENT (HALL CT)</td>
                    <td>Physical Transducer</td>
                    <td>{record.currentRms != null ? `${record.currentRms} A RMS` : '—'}</td>
                    <td>Real Power: {record.power != null ? `${record.power} kW (V × I)` : '—'}</td>
                    <td><Badge status="HEALTHY" size="sm" /></td>
                  </tr>
                  <tr>
                    <td className="font-bold">VOLTAGE (PT)</td>
                    <td>Physical Transducer</td>
                    <td>{record.voltageRms != null ? `${record.voltageRms} V RMS` : '—'}</td>
                    <td>{record.voltageRms != null ? 'Nominal AC Input' : 'No data'}</td>
                    <td><Badge status="HEALTHY" size="sm" /></td>
                  </tr>
                  <tr>
                    <td className="font-bold">TEMPERATURE (PT100)</td>
                    <td>Physical Transducer</td>
                    <td>{record.temp != null ? `${record.temp} °C` : '—'}</td>
                    <td>Rise: {record.tempRise != null ? `+${record.tempRise} °C` : 'BASELINE: INSUFFICIENT REAL DATA'}</td>
                    <td><Badge status={record.temp > 70 ? 'WARNING' : 'HEALTHY'} size="sm" /></td>
                  </tr>
                  <tr style={{ background: '#f8fafc' }}>
                    <td className="font-bold text-amber">ESTIMATED RPM</td>
                    <td>Derived (Vibration 1X × 60)</td>
                    <td>{record.estimatedRpm && record.estimatedRpm !== '—' ? `${record.estimatedRpm} RPM` : 'Not available'}</td>
                    <td>Experimental Derived Metric</td>
                    <td><Badge status="INFO" label="DERIVED" size="sm" /></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Diagnostic & Verification Notes */}
          <div className="modal-section-card">
            <div className="section-card-title">
              <ShieldAlert size={13} className="text-blue" />
              <span>ANALYSIS SUMMARY & AUDIT LOG</span>
            </div>
            <div className="audit-text font-mono text-xs">
              <p>• Data record generated via <strong>{record.mode}</strong> pipeline.</p>
              <p>• Target asset: <strong>{record.motorId} ({record.motor})</strong>. Telemetry processed via common SignalProcessingEngine.</p>
              <p>• Operator / System: <strong>{record.operator || 'Engineering Console'}</strong>.</p>
              <p>• Telemetry integrity: All 4 physical transducer channels verified numeric without corrupted records.</p>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="modal-footer">
          <div className="font-mono text-xs text-muted">
            AUDIT RECORD ID: {record.recordId} • MOTOR: {record.motorId}
          </div>
          <button className="eng-btn eng-btn-primary" onClick={onClose}>
            CLOSE
          </button>
        </div>
      </div>

      <style>{`
        .modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(15, 23, 42, 0.45);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 1000;
          backdrop-filter: blur(1.5px);
        }

        .modal-container {
          background: #ffffff;
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-md);
          width: 90%;
          max-width: 820px;
          max-height: 85vh;
          display: flex;
          flex-direction: column;
          box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
        }

        .modal-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px 18px;
          border-bottom: 1px solid var(--border-subtle);
          background: #f8fafc;
          border-top-left-radius: var(--radius-md);
          border-top-right-radius: var(--radius-md);
        }

        .modal-title-group {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .modal-title {
          font-size: 13px;
          font-weight: 700;
          color: var(--text-main);
          letter-spacing: 0.03em;
        }

        .modal-close-btn {
          border: none;
          background: transparent;
          color: var(--text-muted);
          cursor: pointer;
          display: flex;
          padding: 4px;
          border-radius: var(--radius-sm);
        }

        .modal-close-btn:hover {
          color: var(--text-main);
          background: #e2e8f0;
        }

        .modal-body {
          padding: 18px;
          overflow-y: auto;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .modal-meta-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 10px;
        }

        @media (max-width: 768px) {
          .modal-meta-grid {
            grid-template-columns: 1fr;
          }
        }

        .meta-box {
          background: var(--bg-card-subtle);
          border: 1px solid var(--border-subtle);
          padding: 8px 10px;
          border-radius: var(--radius-sm);
          display: flex;
          flex-direction: column;
          gap: 3px;
        }

        .meta-label {
          font-size: 8.5px;
          font-weight: 700;
          color: var(--text-muted);
          letter-spacing: 0.05em;
          text-transform: uppercase;
        }

        .meta-value {
          font-size: 12px;
          color: var(--text-main);
        }

        .modal-section-card {
          border: 1px solid var(--border-subtle);
          border-radius: var(--radius-sm);
          overflow: hidden;
        }

        .section-card-title {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 8px 12px;
          background: #f8fafc;
          border-bottom: 1px solid var(--border-subtle);
          font-size: 10.5px;
          font-weight: 700;
          letter-spacing: 0.04em;
          color: var(--text-main);
        }

        .audit-text {
          padding: 12px;
          line-height: 1.6;
          color: var(--text-main);
        }

        .audit-text p {
          margin: 4px 0;
        }

        .modal-footer {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px 18px;
          border-top: 1px solid var(--border-subtle);
          background: #f8fafc;
          border-bottom-left-radius: var(--radius-md);
          border-bottom-right-radius: var(--radius-md);
        }
      `}</style>
    </div>
  );
};
